WITH CTE AS (

select 

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
DAY(TO_TIMESTAMP(STARTED_AT)) AS DAY_STARTED_AT,
YEAR(TO_TIMESTAMP(STARTED_AT)) AS YEAR_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) AS DAYOFWEEK,

CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESS_DAY'
END AS DAY_TYPE,

CASE
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
    THEN 'WINTER'
    WHEN  MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUM'
    END AS SEASON_OF_YEAR

FROM 
{{ source('demo', 'bike') }}
where STARTED_AT !='started_at'
)

select 
* 
from CTE