WITH CTE AS (

select 

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
DAY(TO_TIMESTAMP(STARTED_AT)) AS DAY_STARTED_AT,
YEAR(TO_TIMESTAMP(STARTED_AT)) AS YEAR_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) AS DAYOFWEEK,

{{ date_type('STARTED_AT') }} AS DAY_TYPE,


{{ get_season('STARTED_AT') }} AS season_of_year


FROM 
{{ ref('stg_bike') }}
where STARTED_AT !='started_at'
)

select 
* 
from CTE